name: smart_sync
description: A Flutter package for seamless synchronization between local
  storage and remote servers with offline-first support.
version: 0.1.0
homepage: https://github.com/o-Proteus-o/smart_sync.git
repository: https://github.com/o-Proteus-o/smart_sync.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  connectivity_plus: ^3.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  meta: ^1.8.0
  path_provider: ^2.0.11
  sqflite: ^2.2.8
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.3.2
  test: ^1.21.4
